### ISSUE TITLE
Написать задание на разработку

### ISSUE THREAD

**Issue by wldmr-key** [toshaklg/course_project#1]
3-5 предложений по существу работы

**Comment by toshaklg** [comment]
Программа автоматизированного расчёта региональных стандартов разрабатывается для министерства тарифного регулирования Калужской области и предназначена для применения в профильных отделах министерства тарифного регулирования Калужской области. Расчет регионального стандарта производится по каждому из 280 муниципальных образований Калужской области на основе сведений, которые вносятся в акт, о выбранном среднем многоквартирном (индивидуальном) жилом доме, являющимся наиболее типичным (по конструктивным особенностям, степени благоустройства и поставщикам коммунальных ресурсов) для конкретного муниципального образования. Акты содержат информационные сведения о выбранных домах и их параметры (напр. поставщики коммунальных услуг и тарифы), которые необходимы для дальнейшего расчёта размера регионального стандарта в конкретном муниципальном образовании. На основании актов в министерстве проводят расчёт регионального стандарта.

**Comment by wldmr-key** [comment]
:) поздновато - задание-то я уже, похоже, утвердил...
