### ISSUE TITLE
Реализация БД для справочников.

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#11]
Владимир Юрьевич, есть вопрос.
Я решил начинать делать сначала БД, а затем буду прикручивать к ней само приложение.
Вот у меня есть логическая схема таблиц-справочников:
[Картинка](https://puu.sh/BFCSr.png)
_Вроде на ней остановились, но есть проблема, как реализовывать разные версии справочников?_ 
Я то ли забыл, то ли мы с Вами об этом тогда не говорили.

У меня есть предположение, сделать таблицу из двух столбцов - версия справочника и внешний ключ на саму строчку справочника. Но!, строчек в справочнике много, и со временем или при изменении одной строки и обновлении номера версии их станет в разы больше, что, по-моему, не очень хорошо. Что с этим сделать можно?

@wldmr-key

**Comment by toshaklg** [comment]
Чтож, попробуем...

>Что такое версия справочника?

Под этим я понимаю совокупность справочных таблиц с конкретными данными в них.

>Откуда она появляется?

Не очень понятно, но, по-сути, номер версии задаётся разработчиком (или администратором при обновлении таблиц).

>Когда возникает нужда в ней?

При выполнении расчёта.

>Как это проявится в интерфейсе?

Хм, я себе представляю это как, например, выпадающее меню со списком версий (напр. 1.1; 1.2; 2.1 и т.д.)

>Исправление ошибки тарифа одного предприятия - это новая версия?

По-хорошему - да. Потому что по таблице могли быть сделаны расчёты, потом исправили ошибку, и новые расчёты будут идти с новым значением, что может сильно повлиять на результат. По итогу может получится половина расчётов со, скажем, очень высоким региональным стандартом, а другая половина с очень низким при одинаковой версии справочника. 

>Какие проблемы/действия это влечет в зависимости от времени, когда это происходит?

Не понял вопрос, что происходит? Изменение версии? 
Если так, то я думаю, что создаётся новая таблица для конкретной обновлённой таблицы, вносится в БД и хранится рядом со старой.

@wldmr-key

**Comment by wldmr-key** [comment]
>Что такое версия справочника?
Под этим я понимаю совокупность справочных таблиц с конкретными данными в них.

Это справочники, а не версия справочника

>Откуда она появляется?
Не очень понятно, но, по-сути, номер версии задаётся разработчиком (или администратором при обновлении таблиц).

>Как это проявится в интерфейсе?
Хм, я себе представляю это как, например, выпадающее меню со списком версий (напр. 1.1; 1.2; 2.1 и т.д.)

Тебе людей совсем не жалко? )) Ты представляешь, какой это адъ?

Все остальное вполне хорошо до момента:
>Какие проблемы/действия это влечет в зависимости от времени, когда это происходит?
Не понял вопрос, что происходит? Изменение версии?
Если так, то я думаю, что создаётся новая таблица для конкретной обновлённой таблицы, вносится в БД и хранится рядом со старой.

Проанализируй процессы в системе:
подготовка справочников -> заполнение актов -> расчет -> выпуск приказа
на следующий год - все то же самое. При такой последовательности версия справочника зависит только от года. При подготовке справочника изменился один тариф или сто никакой роли не играет - ни на заполнение актов, ни на расчет, ни на уже выпущенный приказ это не повлияет.

Но, жизнь есть жизнь - что произойдет, если найдена ошибка и понадобилось изменить что-то в момент, когда уже начато заполнение актов (кстати, когда оно начинается - у тебя про это не написано. В любой момент?), или начат расчет (кстати, когда он происходит?), или выпускается дополнение к приказу (кстати...)?

**Comment by toshaklg** [comment]
>При такой последовательности версия справочника зависит только от года. 

При такой - да, я думал немного о другой.
Тогда версия справочника - текущий год.

>когда уже начато заполнение актов (кстати, когда оно начинается - у тебя про это не написано. В любой момент?)

У меня есть сроки в исследовательской части. Они недостаточно полные, да?  
_Календарные сроки этапов:_
_1.	Получение заполненных Актов от всех муниципальных образований – до 1 февраля;_
_2.	Выпуск региональных стандартов – до 1 марта._

А если вот так: 
1. Заполнение и получение заполненных Актов от всех муниципальных образований – с 1 января до 1 февраля;
2. Выполнение расчётов по актам - с 1 февраля до 10 февраля.
3. Выпуск региональных стандартов - с 10 февраля до 1 марта.
4. Выпуск дополнения к приказу - с 1 марта до 10 марта.

>Но, жизнь есть жизнь - что произойдет, если найдена ошибка и понадобилось изменить что-то в момент, когда уже начато заполнение актов...

Хм, значит будут внесены изменения в справочники регионам придётся исправить этот граф. У меня пока только такое предположение.
@wldmr-key

**Comment by wldmr-key** [comment]
возвращаемся: что такое версия справочника?
>А если вот так:

можно и так. Правда, что такое расчет? Почему он 10 дней делается? ))

>Хм, значит будут внесены изменения в справочники регионам придётся исправить этот граф. У меня пока только такое предположение.

опять регионам!!!!! Всем? При любом изменении? И что там с версиями?

**Comment by toshaklg** [comment]
>возвращаемся: что такое версия справочника?

Нуууу, то что я написал раньше - лучшее, как мне кажется, что я могу про это сказать.
`Под этим я понимаю совокупность справочных таблиц с конкретными данными в них.`

Можно еще сказать, что это вариант изложения информации...
Да и я думаю, что совокупность таблиц - есть справочник, а его версия определяется текущим годом и составом таблиц. Не знаю как еще понятнее это объяснить.


>можно и так. Правда, что такое расчет? Почему он 10 дней делается? ))

Да это несколько кнопок нажать, по - хорошему. Выбрать акты, выбрать справочник (или он сам автоматически установится) и нажать кнопку выполнения расчёта.
что такое расчет? - Расчёт регионального стандарта по акту.

>опять регионам!!!!! Всем? При любом изменении? И что там с версиями?

Ну я привык и не могу отвыкнуть. Муниципальным образованиям, конечно. 

>Всем?

Нет, не всем, только тем у кого этот пункт был выбран. 

>При любом изменении?

При изменении значения тарифа. 

>И что там с версиями?

Вверху

**Comment by wldmr-key** [comment]
Поставлю вопрос прямо: версия - это сущность или атрибут. В твоем изложении - это суперсущность (совокупность таблиц) и для ее воплощения, несомненно, нужны какие-то суперсредства ))

**Comment by toshaklg** [comment]
@wldmr-key Атрибут конечно

**Comment by toshaklg** [comment]
wldmr-key И я тут подумал, что если атрибут, то он должен быть в логической схеме, а у меня его нету

**Comment by wldmr-key** [comment]
ЙЕС!!!!!!!!!

**Comment by toshaklg** [comment]
@wldmr-key 
Да, я думал по-другому
Вот, посмотрите?
[Схема](https://puu.sh/BIhfQ.png)

**Comment by toshaklg** [comment]
@wldmr-key 
Юрий Владимирович, вот новая, немного переделанная [схема](https://puu.sh/BKQ8M.png). 
Из разговора с Вами получается так, версия справочника - дата. При выполнении расчёта пользователь будет выбирать дату, по состоянию на которую справочник будет актуальным.
При обновлении справочной таблицы - будет добавляться одна строчка и указываться новая дата (версия) для этой строчки. Для таблиц со сложными справочниками - будет добавляться новый сложный объект с новой датой.

**Comment by wldmr-key** [comment]
хорошо, но здесь - самое время задуматься - над простым и сложным вопросами
простой: время калькуляции нужно ли в строке? оно ведь общее для всего расчета?
сложный: а что такое связи между справочниками (и нормативом Т7) и строкой расчета? Являются ли они реляционными? Что происходит с нормализацией?

**Comment by toshaklg** [comment]
@wldmr-key 
>простой: время калькуляции нужно ли в строке? оно ведь общее для всего расчета?

Вероятно, что не нужно. Оно общее для расчёта.
>сложный: а что такое связи между справочниками (и нормативом Т7) и строкой расчета? 

Тут совсем сложно -_-
Ну связи, которые обозначают, что этот справочник участвует в расчёте. Точнее даже, он участвует в выполнении расчёта, а не непосредственно в самом расчёте. (Я так понимаю, тут чего-то не хватает).

>Являются ли они реляционными?

не понял?

>Что происходит с нормализацией?

Её нет

**Comment by wldmr-key** [comment]
1) время калькуляции в строке
2) "являются ли они реляционными" - означает - собираешься ли ты пользоваться механизмами СУБД  для поддержания ссылочной целостности. Варианты ответа:
а) да
б) буду пользоваться встроенными процедурами
в) буду это делать на слое бизнес-логики
г) она не нужна, связь используется только на момент расчета и потом про нее можно забыть
На самом деле, последнее означает, что связи нет (в смысле логической схемы)
Любой из ответов можно обосновать. Поэтому, я и назвал это сложным вопросом

**Comment by toshaklg** [comment]
@wldmr-key 
>время калькуляции в строке

Не нужно, будет одно общее для расчёта

>"являются ли они реляционными"

Тут я больше склоняюсь к Г, потому что оно так и работает. Как обосновывать? Так и говорить, что такой принцип работы?

**Comment by wldmr-key** [comment]
да, так и говорить. Расчет является производной таблицей - практически это "снимок" заданной ситуации, а не данные

**Comment by toshaklg** [comment]
@wldmr-key Вот, схема теперь должна быть правильной

![draw io_2018-10-25_20-30-40](https://user-images.githubusercontent.com/43007372/47518920-ee535c00-d894-11e8-96b0-0b7d33847614.png)

**Comment by wldmr-key** [comment]
ну да! Только еще потренироваться ее правильно объяснять. А еще лучше описывать

**Comment by toshaklg** [comment]
Решено
