### ISSUE TITLE
Оформление РПЗ + внос актов в БД + алгоритм расчёта [07/11/18 - 14/11/18]

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#15]
- [x] Нужно начинать оформлять и собирать РПЗ

- [x] Алгоритм внесения созданных актов в БД

- [x] Алгоритм расчёта для актов

**Comment by toshaklg** [comment]
@wldmr-key

А что писать в ведении?)
В методичке ничего не написано

**Comment by wldmr-key** [comment]
ну что обычно пишут во введениях - какую-нить шнягу об аццкой актуальности проблемы

**Comment by toshaklg** [comment]
Решено
