### ISSUE TITLE
Оформление РПЗ + алгоритм расчёта [14/11/18 - 30/11/18]

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#17]
По моим подсчётам, у меня осталось оформить РПЗ и сделать алгоритм расчёта, который уже в процессе. Это, по сути, с прошлого спринта и остаётся до конца.

- [x] Введение РПЗ

- [x] Сборка РПЗ

- [x] Оформление листов А3

- [x] Алгоритм расчёта

**Comment by toshaklg** [comment]
@wldmr-key
[что это](https://puu.sh/C60au.png)
По расчёту, не пойму и не могу вспомнить, что означают эти Акт, Гр, стр...

**Comment by wldmr-key** [comment]
акт 1 графа  (столбец) 4 строка 1.3

**Comment by toshaklg** [comment]
Так получше, спасибо

**Comment by toshaklg** [comment]
@wldmr-key 
А что насчёт титульника для РПЗ? Мы в начале года сдавали что-то подписанное на кафедру, но то ли это за практику, то ли для курсовой, уже не помню

**Comment by toshaklg** [comment]
@wldmr-key 
Начал собирать всё, что скажете?
[сборка](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9A%D0%9F%20%D0%91%D0%94%20%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20-%20%D0%9E%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%B0%D0%BF%D0%B4%D0%B5%D0%B9%D1%82%D0%B5%D0%B4.docx)

**Comment by wldmr-key** [comment]
1) насчет титульника - [здесь](https://sites.google.com/site/sapr91bd/classroom-news/titulnyelisty2018) лежат все актуальные образцы - если не затруднит - передай своим коллегам

**Comment by wldmr-key** [comment]
По сборке:
1) научись пользоваться Word. Почему у тебя все заголовки первого уровня? От этого и оглавление такое страшное
2) "Рисунок 1 – Концептуальная схема данных
	На рисунке 2 представлена концептуальная схема данных предметной области." - номера не стыкуются
3)концептуальная схема - что за ОКРУГА??!!!!

остальное - то ли нормально, то ли я перестал отслеживать. Почему литература появляется самой последней? Ты ничего не читал? ))

**Comment by wldmr-key** [comment]
все нормально. Литература и заключение за тобой.
приготовься к ответу на защите на мой вопрос - реляционная ли у тебя база данных ))
надеюсь я смогу сам убедиться в работоспособности твоей программы, следуя readme

**Comment by toshaklg** [comment]
Я перепроверю его, может с момента написания уже не совсем соответствует,
хотя должно

пн, 3 дек. 2018 г., 9:35 Vladimir notifications@github.com:

**Comment by toshaklg** [comment]
@wldmr-key а за что мне -5?)

**Comment by wldmr-key** [comment]
у меня есть даже два ответа:
а) чтобы остальные не комплексовали
б) не готов один из пунктов на этот этап - Презентация (альфа)

**Comment by toshaklg** [comment]
@wldmr-key 
[Презентация](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pptx)

Завтра покажу/спрошу по ней ещё
