### ISSUE TITLE
Допилить презентацию

### ISSUE THREAD

**Issue by wldmr-key** [toshaklg/course_project#18]
В текущем виде она слишком большая. И кое-чего в ней не хватает:
Не хватает ритуальных слайдов с целью и задачами работы
И финальных - выводы и спасибо за внимание и последнего слайда со ссылками на все
Времени тебе на все, очевидно не хватит
Часть слайдов можно отнести на графику, часть оставить за пределами презентации и показать, если возникнут вопросы
В тексте (на слайде этого и не нужно) не хватает определения региональных стандартов
Намеченные мной жертвы: слайды 3(?), 4, 6, 7(?),  8(?),  9,  11,  13, 15
@toshaklg

**Comment by toshaklg** [comment]
@wldmr-key 
С 3-4 согласен, можно убрать,
6 - ну да, наверное тоже,
7 - там алгоритм обработки, как-то жалко его, 
8 - сам не знаю, но чтобы показать что я делал он, он мне кажется, подходит,
9-11 я так понял, можно заменить 10,
13-15 да, можно убрать

[Презентация](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pptx)

Всё после "Спасибо за внимание" - слайды на всякий случай.

**Comment by wldmr-key** [comment]
Нормально, может, и успеешь ))
я бы поставил третий слайд перед вторым, чтобы рассказ был более складным и цель не возникала на пустом месте

**Comment by toshaklg** [comment]
Подписал рисунки, написал вывод
@wldmr-key 
[Презентация](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pptx)

**Comment by wldmr-key** [comment]
слушай, а рисунки точно нужно подписывать? Раньше просто слайды нумеровали...
Я раньше просмотрел или кратность дуг (1-ко-многим) на концептуальной схеме недавно пропала? 
В выводах по программе импорт справочников решил не упоминать?

**Comment by wldmr-key** [comment]
так лучше. Но
не думаю, что есть связь между пользователем министерства и строкой расчета (кстати в логической схеме у тебя ее нет)
уверен, что между  сводной таблицей и строкой расчета связь многие ко многим

**Comment by toshaklg** [comment]
@wldmr-key 
Действительно, не обратил внимание
[тут](https://puu.sh/CeWDA.png)

**Comment by toshaklg** [comment]
Я оставлю нумерацию картинок, ну просто в презентации по практике они тоже нумеровались.
Потом переделал титульник на более культурный, поправил шрифты и там по мелочи дописал определение.
С [презентацией](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pptx) вроде бы всё.
Исправил в рпз картинку концептуальной схемы, больше ничего
@wldmr-key

**Comment by wldmr-key** [comment]
отлично, можно отдыхать

**Comment by wldmr-key** [comment]
Ну, во-первых, не другим, а другой. Во-вторых, ты же и так узнал. В-третьих, у тебя на логической схеме стрелки от resources тоже склеились, но ты же и без меня заметил, да?

**Comment by toshaklg** [comment]
Ну а чего бы им не склеиться? Разве суть изменяется?
