### ISSUE TITLE
Заключение/Выводы к презентации

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#19]
Я думаю, что вот это напишу в заключении к рпз и в выводе к презентации. @wldmr-key

-В ходе выполнения курсовой работы была исследована и описана предметная область и проведён анализ объекта автоматизации. Была спроектирована концептуальная и логическая схемы базы данных, разработаны алгоритмы обработки данных и методы их хранения. Результатом курсовой работы является работоспособная серверная компонента системы с примером расчёта тестового акта и взаимодействием с разработанной базой данных.

Только мало как-то, как мне кажется...

**Comment by wldmr-key** [comment]
нормально
