### ISSUE TITLE
Литература

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#20]
1. Шнырёв, С.Л.  Базы данных: учебное пособие для вузов - М. :
НИЯУ МИФИ, 2011. — 224 с. — Режим доступа:
http://e.lanbook.com/book/75809
2. Ревунков, Г.И. Базы и банки данных - М.: МГТУ им. Н.Э.
Баумана, 2011. — 68 с. — Режим доступа:
http://e.lanbook.com/book/52425
3. Ревунков, Г.И. Проектирование баз данных - М.: МГТУ им.
Н.Э. Баумана, 2009. — 20 с. — Режим доступа:
http://e.lanbook.com/book/52390
4. Кудрявцев, К.Я. Создание баз данных: учебное пособие —
М.: НИЯУ МИФИ, 2010. — 155 с. — Режим доступа:
http://e.lanbook.com/book/75822
5. Джуба С., Волков А. Изучаем PostgreSQL10 - М. :
ДМК Пресс, 2018. — 400 c. 
6. Тарасов, С.В. СУБД для программиста. Базы данных изнутри — М. :
Солон-Пресс, 2015.  — 320 с.

**Comment by toshaklg** [comment]
@wldmr-key

**Comment by wldmr-key** [comment]
)) пойдет
