### ISSUE TITLE
Титульники

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#21]
[Задание на курсовую](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%BA%D1%83%D1%80%D1%81%D0%BE%D0%B2%D1%83%D1%8E%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83.docx)

А в задании на курсовую, что писать в техническом задании? Не соображу
@wldmr-key

[РПЗ титульник](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%A0%D0%9F%D0%97%20%D1%82%D0%B8%D1%82%D1%83%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA.doc)

**Comment by wldmr-key** [comment]
да то же, что и раньше

**Comment by toshaklg** [comment]
@wldmr-key 
Я дописал там техническое задание, по сути то, что делал.
[Подходит?](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%BA%D1%83%D1%80%D1%81%D0%BE%D0%B2%D1%83%D1%8E%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83.docx)

**Comment by wldmr-key** [comment]
нормально
