### ISSUE TITLE
Листы

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#22]
@wldmr-key

[Алгоритм обработки](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%9C%D0%9E.jpg)

[Концептуальная схема данных](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20.jpg)

[Логическая схема данных](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%9B%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20.jpg)

[Структура классов](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2%20%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.jpg)

[Сценарии использования](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F.jpg)

**Comment by toshaklg** [comment]
@wldmr-key 
Поправил концептуальную схему и решил почитать методичку, в которой нашёл как правильно подпись листа делать)
Вот переделал, вроде тоже готовы.
Скрин с excel я не буду на листы выносить, не могу его в адекватном масштабе сделать, чтобы на листе хорошо выглядело
Вот новые
[Алгоритм обработки](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%9C%D0%9E.jpg)

[Концептуальная схема](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20.jpg)

[Логическая схема](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%9B%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20.jpg)

[Структура классов](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2%20%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F.jpg)

[Сценарии использования](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9B%D0%98%D0%A1%D0%A2%D0%AB/%D0%901%20-%20%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F.jpg)

**Comment by wldmr-key** [comment]
о! совсем круто стало
