### ISSUE TITLE
Техническое задание 2019

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#24]

**Comment by toshaklg** [comment]
@wldmr-key
Вот тут ТЗ, осталось введение написать
Что скажете? 
[Тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.docx)

**Comment by toshaklg** [comment]
UP: написал введение

**Comment by wldmr-key** [comment]
По заданию на разработку:  "Выполнить исследование процессов взаимодействия с приложением".  Взаимодействия? Кого? Что будет в результате исследования? Проектировать клиентское приложение будешь?
По ТЗ. 
титульник по ГОСТ?
Введение - это что еще за "приложения к годовой отчётности"?!
Функциональные характеристики описаны максимально неконкретно. Что относится к клиентскому приложению, что к административным функциям. 
Веб-реализация вообще, судя по ТЗ не нужна. Это как? Ты собираешься еще раз мой эксель продаьть? ))

**Comment by toshaklg** [comment]
@wldmr-key А что подразумевается под "административными функциями"?
И я постарался расписать функции клиентского приложения, что скажете?
[ТУТ](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.docx)

**Comment by wldmr-key** [comment]
в клиентских приложениях работают сотрудники министерства и МО. К административным функциям относится импорт  данных для справочников и расчетов, возможно, модификация параметров конфигурации

**Comment by wldmr-key** [comment]
функциональные требования близки к нормальным. Проанализируй рекомендуемые ГОСТ подразделы 3. Ты уверен, что стоит их все кроме двух выбросить. Из чего следует, что ты будешь разрабатывать веб-приложение?

**Comment by toshaklg** [comment]
@wldmr-key 
Я, наверно, понял про что Вы, так что добавил пункт 3.3 Требования к составу и параметрам технических средств. [Вот](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.docx)

Но ГОСТ гласит: "В подразделе "Требования к составу и параметрам технических средств" указывают необходимый состав технических средств с указанием их основных технических характеристик."
Что за технические характеристики?

**Comment by wldmr-key** [comment]
Нет, ГОСТ указывает, что все, что ты написал (правильно) относится к подразделу "Требования к информационной и программной совместимости". Так что перемещай туда. Технические характеристики можно либо не уточнять, либо сослаться на достаточность для исполнения программных
Все остальное нормально за исключением невидимого титульного листа
И напиши задание на выполнение КР

**Comment by toshaklg** [comment]
@wldmr-key 
Исправил это и еще пункт по этапам, а то там неправильно было написано - [ТЗ](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BE%D0%B5%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.docx)

Задание на выполнение КР у меня на титульнике написано, это разве не оно?
[Титульник](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%BA%D1%83%D1%80%D1%81%D0%BE%D0%B2%D1%83%D1%8E%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83%202019.docx)

**Comment by wldmr-key** [comment]
ок, хорошо
