### ISSUE TITLE
НИР

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#25]
@wldmr-key
Владимир Юрьевич, вот [тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9D%D0%98%D0%A0/%D0%9D%D0%98%D0%A0%202019.docx) вторая часть в НИРе.
И мне кажется, что там слишком много кода...
Что скажете?

**Comment by toshaklg** [comment]
Я думаю, может не весь код показывать, а только то, что изменилось?
@wldmr-key

**Comment by wldmr-key** [comment]
нет, мне не показалось, что кода много. Пока оставим так...
Замечания:

> Так как SQL-запросы к базе данных для тарифов и объектов легко поддаются ручной отладке и не занимают много времени, сконцентрируемся на устранении лишних преобразований и алгоритме выбора норматива

В контексте TDD - это очень опрометчивое высказывание, так как
1) что-то может произойти с СУБД (это внешняя для тебя программа, поэтому., ты **должен** предполагать, что может произойти все, что угодно
2) в СУБД может нарушиться целостность

Вторую проблему ты закрываешь (надеюсь) подстраховкой .FirstOrDefault(), а, вот, при наличии первой твой метод ляжет. Поэтому, возможно, имеет смысл упомянуть, что у тебя предусмотрены средства борьбы с этим (например внешний обработчик исключений - расчет в любом случае, ведь, придется прекращать)

Сильно бросается в глаза **Temlete1** - это ж Template имелся в виду? Кстати, один из легких и эффективных элементов рефакторинга - приведение имен к одному стандарту.

По структуре кода (читаемости, фактически) сейчас является более можной тенденции к уменьшению вложенности операторных скобок
Я бы так писал:
```
   if (_evAct.mkdH._water == null || _evAct.mkdH._water.ProviderWaterForGVS == null
          || !_evAct.mkdH._water.CentralGVS )
          return 0;
   //Тариф
   double _T3Tariff = db.simpleResRef.FirstOrDefault(x => x.name == "Hvs" 
     && x.district_id == _evAct.mkdH.Locality 
     && x.factory == _evAct.mkdH._water.ProviderWaterForGVS 
     && x.halfYear == _hf).rate;
   if (_T3Tariff == 0) return 0; // (или raise - потеря целостности)
и так далее..

```

что-то на меня жуть нагнал твой способ поиска значений в таблице через двойной цикл. А, по индексам, не?

**Comment by toshaklg** [comment]
@wldmr-key Что за индексы, не понял?
Там двумерный массив, у которого по вертикали изменение температуры, а по горизонтали изменение набора параметров.
![EXCEL](https://user-images.githubusercontent.com/43007372/65300010-9becef00-db7a-11e9-8535-fa4b4b559bcb.png)

**Comment by wldmr-key** [comment]
по горизонтали у тебя числа от 7 до 0, по вертикали от 60 до 75. Зачем делать перебор в цикле, когда можешь найти сразу по температуре и характеристикам?

**Comment by toshaklg** [comment]
@wldmr-key А, ну понял

**Comment by toshaklg** [comment]
Переписал, переделал, стало еще меньше и компактнее...
Здорово получается, я понимаю, что весь расчёт так-то работает на добром слове


[Тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9D%D0%98%D0%A0/%D0%9D%D0%98%D0%A0%202019.docx)

Что мне написать про покрытие кода тестами? Я как-то особо много не планировал, хотел упомянуть, что при таком подходе юнит тесты покроют все (?) методы для расчёта регионального стандарта. Соответственно интеграционные тесты уже нужно делать отдельно, вне TDD. Вот

**Comment by wldmr-key** [comment]
отлично. По существу - все хорошо.
Необходимо дополнить:
а) введение в задачу. Ты предполагаешь, что все отлично представляют, как считается ГВС. Поверь, это не совсем так ))
б) список литературы (надеюсь, до концепции ТДД ты не сам додумался?)

> хотел упомянуть, что при таком подходе юнит тесты покроют все (?) методы для расчёта регионального стандарта. Соответственно интеграционные тесты уже нужно делать отдельно, вне TDD

Хотел - упомяни. Но, по-моему, у тебя еще контроллеры останутся непокрытыми и, если есть, нетривиальные операции с моделью.

**Comment by toshaklg** [comment]
[НИР](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9D%D0%98%D0%A0/%D0%9D%D0%98%D0%A02019.docx)

@wldmr-key 
Владимир Юрьевич, я написал подробности по расчёту и вывод. Что скажете?
И есть еще вопрос по вот этому:

> Но, по-моему, у тебя еще контроллеры останутся непокрытыми и, если есть, нетривиальные операции с моделью.

Имеется ввиду что мне еще нужно также для контроллеров делать, или что?

**Comment by wldmr-key** [comment]
делать юнит-тесты по контроллерам достаточно полезно, так как это - типовая операция. Более того, именно контроллеры часто разрабатываются по TDD. Можешь этого не делать, но, тогда, не стоит писать про полное покрытие

Текст НИР в принципе нормальный. Нужно вычитать его и согласовать падежи и неуместные слова. Кроме того, стороннему человеку непонятны такие сложности из-за двух простых формул. Поэтому, образование нормативов я бы советовал расписать поподробнее

**Comment by toshaklg** [comment]
@wldmr-key 
Я дописал введение, убрал упоминания про покрытие кода и написал немного поподробнее про нормативы
[Тут](
https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%9D%D0%98%D0%A0/%D0%9D%D0%98%D0%A02019.docx)

**Comment by wldmr-key** [comment]
Нормально. А ссылки в тексте, разве, не нужно расставлять? Картинка твоя? Если нет, то тоже нужна ссылка...

**Comment by toshaklg** [comment]
@wldmr-key Картинку рисовал сам по образцу, которых в интернете тьма. 
А ссылки проставил

**Comment by wldmr-key** [comment]
пойдет

**Comment by toshaklg** [comment]
Отправил, жду
