### ISSUE TITLE
Исследовательская часть

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#26]
@wldmr-key
Владимир Юрьевич, здравствуйте!
Написал [(часть)](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%98%D1%81%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx) исследовательской части, что скажете?
Я в целом не сильно вижу разницы с прошлым годом, но некоторые вещи изменил
И вопрос про "процессы внутри и вне системы" - раньше там было описано как работают и откуда берутся данные для Акта, а что писать сейчас?

**Comment by wldmr-key** [comment]
Концептуальная схема - красивая, но для концептуальности не хватает модальности и кратности связей ))

"Пользователь образования" - коряво. Лучше, уж, пользователь МО, если в клетку не влезает. И принадлежит он не региону. Что такое "регион", заодно?

До введения концептуальной схемы у тебя не определены понятия пользователей и расчета (про акт ты сказал выше). Судя по твоему тексту, ты их находишь ("можно выделить", а можно и не выделять) из схемы (а, где ты находишь схему?). Как ты выделяешь из схемы "акт появляется в списке у пользователя министерства" - загадка...

Я думаю, логику изложения здесь нужно перевернуть: определить понятия, процессы сдачи актов, расчета (без деталей) и сказать, что концептуальная модель данных представлена на рис.

Слова после картинки со сценариями использования понятны тебе и мне. Боюсь, больше никому (что за супер-таблицы и NormLiquidGas?). Изложи здесь человеческим языком - что это такое, на что это похоже. Кстати - процессы вне системы - это формирование этих самых справочников. И твои риски - что они окажутся неправильно сформированными.

все остальное - вполне нормально. Сильно убиваться здесь не стоит, но имеет смысл пригладить текст и включить реальный анализ ситуации

**Comment by toshaklg** [comment]
> Концептуальная схема - красивая, но для концептуальности не хватает модальности и кратности связей ))

Поправил

>"Пользователь образования" - коряво. Лучше, уж, пользователь МО, если в клетку не влезает. И принадлежит он не региону. Что такое "регион", заодно?

Район должен быть, исправил

>До введения концептуальной схемы у тебя не определены понятия пользователей и расчета (про акт ты сказал выше). Судя по твоему тексту, ты их находишь ("можно выделить", а можно и не выделять) из схемы (а, где ты находишь схему?). Как ты выделяешь из схемы "акт появляется в списке у пользователя министерства" - загадка...
Я думаю, логику изложения здесь нужно перевернуть: определить понятия, процессы сдачи актов, расчета (без деталей) и сказать, что концептуальная модель данных представлена на рис.

Хм, ну я поправил, но не уверен на все сто, конечно

>Слова после картинки со сценариями использования понятны тебе и мне. Боюсь, больше никому (что за супер-таблицы и NormLiquidGas?). Изложи здесь человеческим языком - что это такое, на что это похоже. Кстати - процессы вне системы - это формирование этих самых справочников. И твои риски - что они окажутся неправильно сформированными.

Ну да, согласен.
Переписал обычными словами и описал процессы внутри и вне системы.

[Я выделил весь новый текст желтым, чтоб его попроще найти было.](https://github.com/toshaklg/course_project/blob/master/Курсовая%202019%20-%20Course%20Project%202019/РПС/КП%20РПС%20Исследовательская%20часть.docx)

**Comment by wldmr-key** [comment]
лучше. Но про эксель можно было бы сказать поподробнее - на что он похож (какие данные характерны для справочников). Впрочем, не обязательно

**Comment by toshaklg** [comment]
Это значит "да" или "нет"?) Я то я не пойму, переделывать или не надо.
Хотя про ексел я напишу поподробнее

**Comment by wldmr-key** [comment]
видишь, сам все правильно понял ))

**Comment by toshaklg** [comment]
@wldmr-key 
Вот так - 
Справочники и нормативы оформленные в EXCEL представляют из себя таблицы схожей структуры X на Y ячеек, в которых заполняются числовые значения нормативов и тарифов, а также названия предприятий-поставщиков определенного ресурса, если в этом есть необходимость.

**Comment by toshaklg** [comment]
Готово
