### ISSUE TITLE
Проектно-конструкторская часть

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#27]
Начал🥇

**Comment by toshaklg** [comment]
@wldmr-key
Владимир Юрьевич,здравствуйте! Я написал частично проектно-конструкторскую часть: [ТУТ](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx)

Я не хочу в РПС много писать про алгоритмы обработки в "3.2. Разработка алгоритмов обработки информации", чтобы написать это в курсовой по МИМАПРУ. Так можно? Там у меня как раз там тема рефакторинг связанный с базой данных и структурой приложения. А тут я просто маленький пример привел, как это в целом работает.

Логическую схему в 3.3 я нарисую, вставлю.
И 3.6 Тоже допишу.

Вы еще НИР посмотрите? Он там в своём issue лежит.

**Comment by wldmr-key** [comment]
нормально. "Клиент-серверное" не подразумевает 4 уровня... "Клиент-серверное четырехуровневое" - подразумевает. Правда, это забавно сочетается с "Архитектура приложения представляет собой 2 компоненты – клиент, сервер приложения и БД"

> Для безошибочного заполнения таблиц рекомендуется использовать шаблоны таблиц, поставляемые с системой.

Кому рекомендуется? Что происходит (должно происходить), если в структуре ошибка?

**Comment by toshaklg** [comment]
@wldmr-key 
Доделал проектно-конструкторскую
[Вот тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx)

**Comment by wldmr-key** [comment]
то есть, я правильно понимаю, что в проектно-конструкторской части ты разработкой интерфейсов заниматься не планируешь?

**Comment by toshaklg** [comment]
@wldmr-key 
Я думал того что было будет достаточно
Вот, написал подробнее
[Тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx)

**Comment by wldmr-key** [comment]
я имел в виду, что я не увидел даже упоминания об основных, на мой взгляд, интерфейсах/процессах = заполнение актов, просмотр заполненных актов/рассчитанных значений

**Comment by toshaklg** [comment]
Ну мне словами их описать?

**Comment by wldmr-key** [comment]
да нет, можешь отложить просто

**Comment by toshaklg** [comment]
Не, ну я опишу это подробнее с картинками (наверно), когда смогу сделать нормально интерфейс для этого (форма акта и большая таблица), потому что пока есть проблемы и я не знаю как мне его лучше сделать. Ибо я не хочу его потом переделывать заново

**Comment by wldmr-key** [comment]
я это и имел в виду. Меня насторожило

> Доделал проектно-конструкторскую

**Comment by toshaklg** [comment]
@wldmr-key 
[Вот](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx)

Немного переделал внешне, и сделал первый этап для заполнения актов.
Соответственно, немного расписал для чего это нужно в РПЗ, где интерфейс.
Это так?

**Comment by wldmr-key** [comment]
да, вполне нормально

**Comment by toshaklg** [comment]
Готово
