### ISSUE TITLE
Проектно-технологическая часть

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#28]
@wldmr-key
[Тут](https://github.com/toshaklg/course_project/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B0%D1%8F%202019%20-%20Course%20Project%202019/%D0%A0%D0%9F%D0%A1/%D0%9A%D0%9F%20%D0%A0%D0%9F%D0%A1%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx)

Я написал пока только первый пункт и он, по сути, такой же.

По структуре:

> 4.2. Использование технологии разработки, основанной на тестах
> (TTD). Покрытие системы тестами.

Ну это прям по моему НИРу. Насколько я знаю, я как-то могу сослаться на него, да?
Как мне это сделать?

А насчёт остального не знаю, мне кажется не нужно писать

**Comment by wldmr-key** [comment]
то что есть -  нормально. Что касается ссылок, то, чем заморачиваться со ссылками, проще тупо скопировать оттуда введение и заключение

**Comment by toshaklg** [comment]
@wldmr-key Я думаю, что оставлю это для курсовой по мимапру, а здесь оставлю как есть

**Comment by wldmr-key** [comment]
ок, приемлемо

**Comment by toshaklg** [comment]
Ну, тогда РПЗ готово, по сути. Осталось только собрать

**Comment by toshaklg** [comment]
Собрано
