### ISSUE TITLE
Спринты

### ISSUE THREAD

**Issue by toshaklg** [toshaklg/course_project#5]
--------
1. Исследовательская часть [XX/XX/XX - 19/09/18]
Оформление исследовательской части: 
-постановка задачи проектирования; 
-описание предметной области; 
-анализ аналогов; 
-перечень задач, подлежащих решению в процессе разработки; 
-обоснование выбора инструментов и платформы для разработки.

--------
2. Исследовательская часть 2 [19/09/18 - 26/09/18]
Исправление ошибок исследовательской части.

--------
3. Проектно-конструкторская часть + ошибки исследовательской части [26/09/18 - 03/10/18]
-разработка архитектуры приложения;
-логическая схема базы данных;
-разработка интерфейса взаимодействия пользователя с системой.

--------

**Comment by toshaklg** [comment]
Док к первому спринту и вопросы на почте.
[КП БД Сборка.docx](https://github.com/toshaklg/course_project/files/2394118/default.docx)

**Comment by wldmr-key** [comment]
_ты представляешь, сколько времени мне нужно, чтобы в этом мегадокументе добраться до существа дела? Я доберусь, но не сегодня, но больше так не делай, если тебя интересует результат :)_
Что касается твоих вопросов в письме

> Вы говорили, что обсуждение на гитхаб потом переносится, да? Там всё писать?

не потом!!!! А, сразу после того, как я это сказал!! Зачем все дублировать?

И твои вопросы, на которые я сейчас отвечу, переписывать специально не нужно

> Сущности и отношения, как я понял, это моя логическая схема БД из которой я могу всё взять, да? А что за понятия тогда?

Нет - это концептуальная схема данных предметной области - картинки, которые мы рисовали в самом начале. И объяснение того, что на этих картинках, понятное для непосвященного человека (понятия). Например, что такое региональный стандарт? :)

> 2.3 Процессы внутри и вне системы
> Здесь, описать как взаимодействуют элементы системы... а вне? Как люди всё это осуществляют?

нет. Касательно твоей системы - откуда берутся тарифы, нормативы, формы? С неба спускаются?

> 3 АНАЛИЗ АНАЛОГОВ
> А если таких нет? Ну я не слышал о таких.

Гуглил? Если нет, то погугли. Если да, то и не пиши этот раздел

> Ошибки как-то влияют? Сильно? Вот например сейчас, я сделал часть исследования, но наверняка неправильно 

Неправильно - это ничего не делать. Все остальное - это шаги в правильном направлении

**Comment by toshaklg** [comment]
Я понял, простите.

**Comment by wldmr-key** [comment]
По тексту исследовательской части

Общие сведения:
> Требуется разработать систему автоматизированного расчёта региональных стандартов Калужской области. Система должна принимать, хранить и обрабатывать акты от регионов Калужской области. Система должна предоставлять сводную таблицу по всем актам от регионов Калужской области. Каждый акт характеризуется набором параметров, необходимых для расчёта

И что из этого можно понять? Что такое региональный стандарт? какие в Калужской области есть "регионы"? Для расчета **необходимы** подписи членов комиссии? А они вообще нужны? Объясни деловые процедуры человеческим языком.

---
Выбор инструмента: постгрес - это база данных? точно? Про описание студии и .NET пока промолчу. Прочитай сам и оставь только те слова, которые сможешь объяснить (я имею в виду не только специальные термины, но и такие обороты, как "_небольшой_ _оптимизированной_ среды выполнения CoreCLR" (_поясни выделенные курсивом слова_ - насколько небольшой?, в каких отношениях оптимизированной?). И вывод: 

> выбранные среды разработки полностью удовлетворяет требованиям

какие из требований имеются в виду?

**Comment by toshaklg** [comment]
Док ко второму спринту.
Поправил ошибки и неточности в исследовательской части, оформил "процессы внутри и вне системы".
В планах на спринт еще как минимум одна доработка.
Еще думаю, что нужно написать понятия помимо регионального стандарта, но не знаю какие именно.
[КП БД Исследовательская часть.docx](https://github.com/toshaklg/course_project/files/2408752/default.docx)

**Comment by wldmr-key** [comment]
Намного-намного лучше, но
Определение регионального стандарта  неконструктивно - написано для чего он используется (это хорошо), но не написано что это такое. Следует с эти разобраться... И объяснить всем.
Нуждаются в пояснении деловые процедуры. С чего это МО (у тебя очередной неологизм - "округа" - это еще что такое?) начинают писать акты? Как регулярно они это делают? Одинаков ли процесс каждый год? 
Ты это знаешь, а твои читатели - нет. И не узнают, пока ты это не напишешь и не расскажешь

**Внутри и вне системы**
Правильный раздел, но ты, увлекаясь фактами, забывашь про связки - какие процессы и данные появляются внутри системы, а какие порождаются внешним миром. Ты пишешь 

> Внутри системы используется утверждённая в министерстве тарифного регулирования Калужской области форма акта – Приложение 1. 

ну используется и что. Данные в актах появляются внутри системы?  Форма актов появляется внутри системы? Форма актов может изменяться? Нормативы заполняются внутри системы? Расчеты выполняются в системе? Все? расчеты меняются со временем? Где - в системе или вне ее?

Требования к инструментам нормальные. Обосновывающая часть нормальная по существу, но изложение я бы посоветовал тебе перечитать еще разок и поправить

**Comment by toshaklg** [comment]
@wldmr-key 
Исправил округа. На самом деле там муниципальные районы и муниципальные образования. Дал им определения. Еще в ТЗ поправил их же, ибо однозначности не было.
[КП БД Исследовательская часть.docx](https://github.com/toshaklg/course_project/files/2412602/default.docx)


>Определение регионального стандарта неконструктивно - написано для чего он используется (это хорошо), но не написано что это такое. Следует с эти разобраться...

Я не пойму как это объяснить. Ничего нигде внятного по этому поводу нету.

>Внутри и вне системы

Дополнил, что - форма акта формируется на основе детального анализа каждого муниципального образования с учётом особенностей типичных для образований домов. Добавил "Календарные сроки этапов."

>Данные в актах появляются внутри системы?

Не понял? Комиссия с муниципального образования заполняет данные в актах.

>Форма актов появляется внутри системы?

Тоже не понимаю... Что значит, что она появляется внутри системы? 


Я предполагаю, что сначала идёт анализ муниципальных образований. Осуществляется сбор данных что в них: какие дома, какой материал у домов, какое отопление, прочая информация о доме, степени благоустройства... всё то, что так или иначе влияет на качество жизни людей. 

>Форма актов может изменяться?

Я думаю, что вполне может, но я не могу просто написать, что вот в следующем году форма может быть изменится. Тут тоже, что и в предыдущем, мне кажется. Всё также осуществляется анализ образований, может где-то лучше стало, появилось что-то новое или наоборот сломалось и стало хуже.
То есть я бы сказал так, что в течении года происходит процесс анализа образований, сбор сведений и формулировка/создание нового акта для будущего года. (В течение года осуществляют сбор сведений, подготавливают форму акта, принимают её, образования заполняют её и министерство издаёт региональный стандарт. И так по кругу)

>Нормативы заполняются внутри системы?

Нуууу, наверное. Тоже не понял.

>Расчеты выполняются в системе?

Да. После отправки акта и его приёма все операции осуществляются внутри.

>расчеты меняются со временем?

Да. Каждый год точно, может чаще в зависимости от справочника/версии акта.

Я, на самом деле, поговорил бы об этом в среду на паре.

**Comment by wldmr-key** [comment]
ok, обсудим, держи свои вопросы/ответы наготове

**Comment by toshaklg** [comment]
@wldmr-key, итак, по итогам разговора я понял всё примерно вот так:

1. Форма акта изменяется. Изменяться она может из года в год, при этом сама форма определяется законами и региональными/областными правилами. Сам пользователь форму акта изменять не может. Это всё - вне системы.

2. Региональный стандарт - величина средней оплаты за коммунальные услуги для каждого населённого пункта. Региональный стандарт утверждается в соответствии с п. 6, ст. 159 ЖК РФ и определяет права граждан на субсидии по оплате жилья и коммунальных услуг и расчёте их размеров.

2.1 Субсидия — это материальная помощь, выраженная в денежной или натуральной величине, со стороны государства, местных органов самоуправления или социального фонда.

3. Нормативы и другие справочники(позже уточню конкретно какие) заполняться будут с Excel - файла (Импорт excel файла) - заполняются внутри системы.

4. Данные в актах заполняют регионы - вне системы, расчёты выполняются внутри системы и могут изменяться с течением времени или от версии справочника.

И еще вопросы появились, куда будет правильно это всё написать? я думаю так -
Региональный стандарт, субсидия - это в семантику и основные понятия.
Что форма акта может изменяться - в раздел процессы внутри и вне системы.
Импорт справочников для исследовательской части, как мне кажется, не подходит. В ТЗ?

**Comment by wldmr-key** [comment]
> Форма акта изменяется. Изменяться она может из года в год, при этом сама форма определяется законами и региональными/областными правилами. Сам пользователь форму акта изменять не может. Это всё - вне системы.

точно! Далее буду комментировать, с чем не согласен

> Региональный стандарт - величина средней оплаты за коммунальные услуги для каждого 

точнее, жилищно-коммунальные

> Нормативы и другие справочники(позже уточню конкретно какие) заполняться будут с Excel - файла (Импорт excel файла) - заполняются внутри системы.

"Заполняться" - плохое, неоднозначное слово. Тарифы, большинство справочников и нормативов определяются вне системы. В систему они попадают посредством импорта либо вводятся внутри системы (нужно определить, какие как)

> Данные в актах заполняют регионы - вне системы, расчёты выполняются внутри системы и могут изменяться с течением времени или от версии справочника.

нет. МО будут пользоваться твоей программой (или сейчас пользуются моей) для заполнения актов и, следовательно, этот процесс - внутри. Расчеты, конечно, тоже.

> И еще вопросы появились, куда будет правильно это всё написать? я думаю так -
> Региональный стандарт, субсидия - это в семантику и основные понятия.

да
> Что форма акта может изменяться - в раздел процессы внутри и вне системы.

да
> Импорт справочников для исследовательской части, как мне кажется, не подходит. В ТЗ?

нет. ТЗ готово уже. В исследовательской части есть еще сценарии использования. там им самое место. Да, погугли про use case

**Comment by toshaklg** [comment]
@wldmr-key 
Написал задание на 3 спринт, его тоже по частям делать буду + написал пункт "Сценарии использования" в исследовательской части, посмотрите?
И остальное подправил/дописал.
[КП БД Исследовательская часть.docx](https://github.com/toshaklg/course_project/files/2431788/default.docx)

>нет. ТЗ готово уже. 

Вы на паре говорили, что в ТЗ еще какие-то правки вносить можно будет, что-то такое. Или я не так понял?
