### ISSUE TITLE
Проектно-конструкторская часть + ошибки исследовательской части [26/09/18 - 03/10/18]

### ISSUE THREAD

**Issue by wldmr-key** [toshaklg/course_project#7]
-разработка архитектуры приложения;
-логическая схема базы данных;
-разработка интерфейса взаимодействия пользователя с системой.

**Comment by wldmr-key** [comment]
> написал пункт "Сценарии использования" в исследовательской части, посмотрите?
> И остальное подправил/дописал.
> КП БД Исследовательская часть.docx

навскидку нормально, только к управлению ролями стрелка неправильная

**Comment by toshaklg** [comment]
[КП БД Проектно-конструкторская часть.docx](https://github.com/toshaklg/course_project/files/2434974/-.docx)
@wldmr-key Почитал про проектно-конструкторскую часть... сложновато. Сделал, не без ошибок

**Comment by wldmr-key** [comment]
Почему ты предполагаешь, что читатель твоего труда не знаком с исследовательской частью? Знаком, поэтому, нужно не повторяться, а развивать результаты исследования (можно на них ссылаться, кстати)
Исходя из этой мысли, начало работы можно переделывать чуть менее, чем полностью
Дальше, впрочем, не сильно лучше. Можно сопоставлять твой текст с методичкой и находить отличия.

**Давай, мы сделаем так: работу над проектно-конструкторской частью на этот и следующий спринт я считаю выполненной - ты, действительно, нормально поработал - самое время отложить на недельку. Сейчас ты сосредоточиваешься на прототипе приложения и наступаешь на грабли в этой области.**

А в следующую среду 10 октября я начну занятие с лекции об идеальной проектно-конструкторской части. Она может быть адекватно воспринята только теми, кто уже пытался ее делать

**Comment by wldmr-key** [comment]
я потому и хочу прочитать лекцию, что короткого ответа у меня (сейчас) нет. Логическая схема хороша, интерфейс нормальный. Но все начинается не с регистрации, а с основной функции (у каждого пользователя она своя)
Алгоритм расчета - ну, да. Начнешь делать - отвлечешься от грустных мыслей ;)

**Comment by toshaklg** [comment]
@wldmr-key 
Начал переделывать проектно-конструкторскую часть, что скажете? Не всю, но большую часть.
[КП БД Проектно-конструкторская часть.docx](https://github.com/toshaklg/course_project/files/2476502/-.docx)

**Comment by wldmr-key** [comment]
подробности про эксель вряд ли уместны в части 3.1. Перенеси ее в 3.2
Алгоритм обработки МО хорош для первоначального заполнения. Представь, что в 2019 году село Бабынино переименовалось в село Путино. Как отработает твой алгоритм? Как нам не потерять старые данные?
логическую схему и версии мы уже обсуждали
остальное - или полуфабрикаты, или выглядит правдоподобно

**Comment by toshaklg** [comment]
@wldmr-key 
>подробности про эксель вряд ли уместны в части 3.1. Перенеси ее в 3.2

Что же мне тогда для 3.1 останется? Маленький кусочек после подробностей про Excel?

>Как отработает твой алгоритм? 

Мой алгоритм добавит новое село Путино, которое будет храниться рядом с селом Бабынино.
И я об этом не подумал. Как по-правильному это должно быть? Я так понимаю, что я должен хранить и старое село и новое, но после обновления везде должно использоваться только новое название, так?


>остальное - или полуфабрикаты, или выглядит правдоподобно

Переделывать или нет?

**Comment by wldmr-key** [comment]
> Что же мне тогда для 3.1 останется? Маленький кусочек после подробностей про Excel?

пусть это тебя не смущает. Если тебе больше нечего сказать про структуру, то и не надо

> которое будет храниться рядом с селом Бабынино

кто ж ему скажет, что оно рядом? Я думаю, нужно предъявлять требования к справочнику МО и в случае переименования вводить старое значение в специальном столбце. Тогда алгоритм несколько усложнится.

Могут переименоваться и поставщики коммунальных ресурсов, но не думаю, что это принципиально - здесь целостность не важна.

> Переделывать или нет?

нет

> У меня чувство, что я не туда движусь...

нормально все

**Comment by toshaklg** [comment]
@wldmr-key 
>кто ж ему скажет, что оно рядом? Я думаю, нужно предъявлять требования к справочнику МО и в случае переименования вводить старое значение в специальном столбце. Тогда алгоритм несколько усложнится.

Получается, что для этого нужно изменять таблицу базы данных, так ведь?

А если мне добавить еще одну табличку, которая будет хранить внешний ключ на id образования и там будут лежать все другие возможные названия?

Если нужно будет переименовать, будет загружаться Excel-файл со старым названием и рядом новое. Новое пойдёт в таблицу МО, а старое будет храниться со ссылкой в другой табличке.
 
>Я думаю, нужно предъявлять требования к справочнику МО и в случае переименования вводить старое значение в специальном столбце. 

А как Вы это представляете? Я не очень пойму просто, где этот специальный столбик должен быть.

И мне сейчас уже немного трудоёмко это внедрять...
Это уже минус балл какой-то будет по итогу?

**Comment by toshaklg** [comment]
@wldmr-key 
+ я поправил 3.1/3.2 и мне хочется что-то сделать с 3.6. Хочется перенести туда структуру классов приложения, под описание раздела вроде подходит. 

>Вместе с тем при построении физической схемы имеет смысл выделить ключевые запросы к базе
данных, обосновать применяемые для их оптимизации методы, описать пользовательские представления данных, встроенные процедуры, транзакции и триггеры (если они имеются).

Вот тут
>ключевые запросы к базе данных

их пока нет, но они планируются...

>описать пользовательские представления данных 

что к этому можно отнести? Форму акта можно? Если да, то она уже описана была ранее...

> Исходя из требований предметной области следует проработать и реализовать дисциплину управления контролем доступа, там, где он необходим,

У меня есть такая, её тоже косвенно касался в исследовательской части в 2.4(вроде там)
Еще раз писать не стоит, наверное

**Comment by wldmr-key** [comment]
> Получается, что для этого нужно изменять таблицу базы данных, так ведь?
А если мне добавить еще одну табличку, которая будет хранить внешний ключ на id образования и там будут лежать все другие возможные названия?

да, и даты переименования

> Если нужно будет переименовать, будет загружаться Excel-файл со старым названием и рядом новое. Новое пойдёт в таблицу МО, а старое будет храниться со ссылкой в другой табличке.

>>Я думаю, нужно предъявлять требования к справочнику МО и в случае переименования вводить старое значение в специальном столбце.

>А как Вы это представляете? Я не очень пойму просто, где этот специальный столбик должен быть.

справа? ))

> И мне сейчас уже немного трудоёмко это внедрять...
Это уже минус балл какой-то будет по итогу?

Ну, получишь не 99, а 98. Прямо, проблема! Зато у тебя есть ценный опыт, сколько стоят ошибки проектирования...

> я поправил 3.1/3.2 и мне хочется что-то сделать с 3.6. Хочется перенести туда структуру классов приложения, под описание раздела вроде подходит.

да, можно. ключевые запросы к базе данных. больше ничего из перечисленного тобой не подходит

**Comment by toshaklg** [comment]
@wldmr-key 
[КП БД Проектно-конструкторская часть.docx](https://github.com/toshaklg/course_project/files/2507858/-.docx)

**Comment by wldmr-key** [comment]
1. Вообще-то у тебя не клиент-серверное приложение, которое предполагается двухуровневым. Между сервером приложений и клиентом находится http сервер.
2. Ты решил большую часть наших недельных обсуждений проигнорировать в документе

**Comment by toshaklg** [comment]
@wldmr-key 
Так, а тут я написал про справочник Т7 + переделал уровни приложения. http уровень - пустой, хочется мне что-то туда написать, но не знаю что...
Добавил все части РПЗ в репозиторий, так удобнее Вам? А как мне ссылку на него дать сюда?

**Comment by wldmr-key** [comment]
вот, нет, чтобы сразу вставить [ссылку на документ](https://github.com/toshaklg/course_project/blob/master/%D0%A0%D0%9F%D0%97/%D0%9A%D0%9F%20%D0%91%D0%94%20%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D1%87%D0%B0%D1%81%D1%82%D1%8C.docx), так надо спросить!

 **http уровень - пустой** - нарисуй прямоугольник и напиши обработка http и cgi - это будет чистой правдой

Ниже будут цитаты, которые вызвали мое легкое стилистическое недовольство
**Серверный** уровень **хранит** в себе алгоритмы
подключения к базе данных - _это, действительно, этап?_
ХВС-ГВС - _эти сокращения введены?_
Заполнения актов происходит 
справочник регионов и образований 
все акты с указанием авторства в формате Json
Рисунок 1 – Соответствие справочных таблиц и хранимой в них информации
производится путём импорта и ручного изменения данных через механизмы поддержки СУБД PostgreSQL и внутренним функциям приложения
База данных не предполагает изменения в структуре и приложение не устойчиво к этим изменениям

Я правильно понимаю, что ты нигде ничего не сказал про структуры данных актов (json)? Или я плохо смотрел?

**Comment by wldmr-key** [comment]
видишь, ты сам все понимаешь. Читай внимательнее, что пишешь, а еще лучше давай читать другим.

>>справочник регионов и образований
>Ну да, а как по-другому сказать?

Как отцы основатели - справочник муниципальных районов, справочник муниципальных образований

> А что писать? Что это такое и как работает?

Да, можно и то, и другое, и обоснование, почему именно так (если хочешь)

**Comment by toshaklg** [comment]
@wldmr-key 
Владимир Юрьевич, хотел еще спросить. У меня получается довольно большое количество справочников и нормативов импортируемых с Excel-файлов, которые различаются по структуре. Мне обязательно в проектно-конструкторской части рассматривать все структуры и как их заполнять?

**Comment by wldmr-key** [comment]
нет, можешь привести список и сказать, что они в принципе очень похожи

**Comment by toshaklg** [comment]
Всё решено
